### ISSUE TITLE
Sobre os nomes deste sistema

### ISSUE THREAD

**Issue by xabiercid** [anavallasuiza/adoadomin-transleite#3]
Que nomes teñen as pezas deste framework? Como chegastes a eles?

(explicádenos como chegastes ata eles para que o entendamos mellor, please... se cadra ocórresenos algo tan wai, pero máis breve), :dancers: / @cmoralesweb @ablunier

**Comment by cmoralesweb** [comment]
https://github.com/anavallasuiza/adobadomin

> The name comes from Admin + doado (galician for easy) + adobado (galician for marinated meat... we love BBQs)

Transleite: Translate -> _transleit_ -> vacas, churrasco, etc.

**Comment by cmoralesweb** [comment]
CRUDoado= CRUD (Create Read Update Delete) + doado
